// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package mpc

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Error) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	z.Msg, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "Msg")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Error) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 1
	err = en.Append(0x91)
	if err != nil {
		return
	}
	err = en.WriteString(z.Msg)
	if err != nil {
		err = msgp.WrapError(err, "Msg")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Error) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 1
	o = append(o, 0x91)
	o = msgp.AppendString(o, z.Msg)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Error) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	z.Msg, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Msg")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Error) Msgsize() (s int) {
	s = 1 + msgp.StringPrefixSize + len(z.Msg)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Message) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 5 {
		err = msgp.ArrayError{Wanted: 5, Got: zb0001}
		return
	}
	z.ID, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	z.Func, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "Func")
		return
	}
	err = z.Args.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	err = z.Result.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Result")
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "Error")
			return
		}
		z.Error = nil
	} else {
		if z.Error == nil {
			z.Error = new(Error)
		}
		var zb0002 uint32
		zb0002, err = dc.ReadArrayHeader()
		if err != nil {
			err = msgp.WrapError(err, "Error")
			return
		}
		if zb0002 != 1 {
			err = msgp.ArrayError{Wanted: 1, Got: zb0002}
			return
		}
		z.Error.Msg, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, "Error", "Msg")
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Message) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 5
	err = en.Append(0x95)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	err = en.WriteString(z.Func)
	if err != nil {
		err = msgp.WrapError(err, "Func")
		return
	}
	err = z.Args.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	err = z.Result.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Result")
		return
	}
	if z.Error == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// array header, size 1
		err = en.Append(0x91)
		if err != nil {
			return
		}
		err = en.WriteString(z.Error.Msg)
		if err != nil {
			err = msgp.WrapError(err, "Error", "Msg")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Message) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 5
	o = append(o, 0x95)
	o = msgp.AppendUint64(o, z.ID)
	o = msgp.AppendString(o, z.Func)
	o, err = z.Args.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	o, err = z.Result.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Result")
		return
	}
	if z.Error == nil {
		o = msgp.AppendNil(o)
	} else {
		// array header, size 1
		o = append(o, 0x91)
		o = msgp.AppendString(o, z.Error.Msg)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Message) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 5 {
		err = msgp.ArrayError{Wanted: 5, Got: zb0001}
		return
	}
	z.ID, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	z.Func, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Func")
		return
	}
	bts, err = z.Args.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	bts, err = z.Result.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Result")
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.Error = nil
	} else {
		if z.Error == nil {
			z.Error = new(Error)
		}
		var zb0002 uint32
		zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "Error")
			return
		}
		if zb0002 != 1 {
			err = msgp.ArrayError{Wanted: 1, Got: zb0002}
			return
		}
		z.Error.Msg, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "Error", "Msg")
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Message) Msgsize() (s int) {
	s = 1 + msgp.Uint64Size + msgp.StringPrefixSize + len(z.Func) + z.Args.Msgsize() + z.Result.Msgsize()
	if z.Error == nil {
		s += msgp.NilSize
	} else {
		s += 1 + msgp.StringPrefixSize + len(z.Error.Msg)
	}
	return
}
